name = "JuliaTutorialsTemplate"
uuid = "e088c1bc-e00f-47bb-8742-48f468c16799"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "0.1.0"

[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"

[compat]
Franklin = "0.10"
PlutoStaticHTML = "3.1"
